$-w = false
$: = ["/usr/local/lib/site_ruby/1.8", "/usr/local/lib/site_ruby/1.8/x86_64-linux", "/usr/local/lib/site_ruby", "/usr/lib/ruby/vendor_ruby/1.8", "/usr/lib/ruby/vendor_ruby/1.8/x86_64-linux", "/usr/lib/ruby/vendor_ruby", "/usr/lib/ruby/1.8", "/usr/lib/ruby/1.8/x86_64-linux", "."]
$. = 1593
$KCODE = "NONE"
$-F = nil
$* = ["/home/abaranji/Aptana Studio 3 Workspace/.metadata/.plugins/com.aptana.ruby.core/-673612933/4"]
$stderr = IO.new
$, = nil
$` = nil
$fileutils_rb_have_lchown = nil
$-p = false
$" = ["enumerator.so", "etc.so", "fileutils.rb"]
$$ = 11136
$< = ARGF
$@ = nil
$-v = false
$-i = nil
$deferr = IO.new
$\ = nil
$= = false
$; = nil
$PROGRAM_NAME = "/home/abaranji/Abaranji Files/Aptana_Studio_3/configuration/org.eclipse.osgi/bundles/79/1/.cp/ruby/core_stubber.rb"
$stdout = IO.new
$& = nil
$-d = false
$LOAD_PATH = ["/usr/local/lib/site_ruby/1.8", "/usr/local/lib/site_ruby/1.8/x86_64-linux", "/usr/local/lib/site_ruby", "/usr/lib/ruby/vendor_ruby/1.8", "/usr/lib/ruby/vendor_ruby/1.8/x86_64-linux", "/usr/lib/ruby/vendor_ruby", "/usr/lib/ruby/1.8", "/usr/lib/ruby/1.8/x86_64-linux", "."]
$-a = false
$VERBOSE = false
$FILENAME = "-"
$defout = IO.new
$-0 = "\n"
$+ = nil
$0 = "/home/abaranji/Abaranji Files/Aptana_Studio_3/configuration/org.eclipse.osgi/bundles/79/1/.cp/ruby/core_stubber.rb"
$stdin = IO.new
$~ = nil
$fileutils_rb_have_lchmod = nil
$DEBUG = false
$-I = ["/usr/local/lib/site_ruby/1.8", "/usr/local/lib/site_ruby/1.8/x86_64-linux", "/usr/local/lib/site_ruby", "/usr/lib/ruby/vendor_ruby/1.8", "/usr/lib/ruby/vendor_ruby/1.8/x86_64-linux", "/usr/lib/ruby/vendor_ruby", "/usr/lib/ruby/1.8", "/usr/lib/ruby/1.8/x86_64-linux", "."]
$_ = nil
$-K = "NONE"
$> = IO.new
$/ = "\n"
$' = nil
$-l = false
$LOADED_FEATURES = ["enumerator.so", "etc.so", "fileutils.rb"]
$? = nil
$SAFE = 0
$! = nil
